"""phase milestone + project range

Revision ID: 24b23d15d079
Revises: a2227f80ceba
Create Date: 2026-07-11 14:58:20.083669
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24b23d15d079'
down_revision: Union[str, None] = 'a2227f80ceba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phases', sa.Column('milestone', sa.CHAR(length=7), nullable=True))
    op.add_column('settings', sa.Column('project_start', sa.CHAR(length=7), nullable=True))
    op.add_column('settings', sa.Column('project_end', sa.CHAR(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'project_end')
    op.drop_column('settings', 'project_start')
    op.drop_column('phases', 'milestone')
    # ### end Alembic commands ###
