"""plan_scale setting

Revision ID: 5d3f3a806a49
Revises: 24b23d15d079
Create Date: 2026-07-11 15:40:15.540474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d3f3a806a49'
down_revision: Union[str, None] = '24b23d15d079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('plan_scale', sa.Numeric(precision=8, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'plan_scale')
    # ### end Alembic commands ###
